In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("../data/raw/UA.csv")
df.head()
df.shape

(1537, 40)

In [ ]:
df.isnull().sum().sum()
(df.isnull().sum() / len(df)) * 100

Gender             0.000000
Age                2.342225
Height             2.212101
Weight             2.212101
BMI                2.212101
L1-4               0.000000
L1.4T              0.000000
FN                 0.000000
FNT                0.000000
TL                 0.000000
TLT                0.000000
ALT                0.130124
AST                0.130124
BUN                0.065062
CREA               0.195185
URIC               0.000000
FBG                1.040989
HDL-C              1.106051
LDL-C              0.910865
Ca                 0.130124
P                  0.325309
Mg                 0.195185
Calsium            0.000000
Calcitriol         0.000000
Bisphosphonate     0.000000
Calcitonin         0.000000
HTN                0.000000
COPD               0.000000
DM                 0.000000
Hyperlipidaemia    0.000000
Hyperuricemia      0.000000
AS                 0.000000
VT                 0.000000
VD                 0.000000
OP                 0.000000
CAD                0.000000
CKD                0.000000
Fracture           0.000000
Smoking            0.000000
Drinking           0.000000
dtype: float64

In [ ]:
df.dropna().shape

(1463, 40)

In [ ]:
len(df) - len(df.dropna())

74

In [ ]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

missing_rows = df[df.isnull().any(axis=1)]
missing_rows

,Gender,Age,Height,Weight,BMI,L1-4,L1.4T,FN,FNT,TL,TLT,ALT,AST,BUN,CREA,URIC,FBG,HDL-C,LDL-C,Ca,P,Mg,Calsium,Calcitriol,Bisphosphonate,Calcitonin,HTN,COPD,DM,Hyperlipidaemia,Hyperuricemia,AS,VT,VD,OP,CAD,CKD,Fracture,Smoking,Drinking
40,1,NaN,165.0,60.0,22.038567,0.995,-1.5,0.9510,-0.90,1.0425,-0.40,15.0,18.0,6.11,84.4,385.4,5.54,1.31,3.02,2.01,0.99,0.82,0,0,0,0,1,1,0,0,1,1,0,0,1,0,0,0,1,1
43,1,74.7,177.0,78.0,24.897060,1.431,1.8,0.8410,-1.80,0.9355,-1.20,74.0,29.0,4.30,NaN,551.0,NaN,1.03,4.53,2.31,1.25,0.99,0,0,0,0,1,0,1,1,1,1,0,0,1,0,0,0,0,1
87,1,NaN,NaN,NaN,NaN,1.549,2.7,0.6865,-2.95,0.7175,-2.85,27.0,28.0,5.90,80.4,451.5,4.43,1.95,4.10,2.43,0.91,1.05,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0
117,2,NaN,NaN,NaN,NaN,1.063,-1.0,0.8520,-1.05,0.9985,0.00,28.0,18.0,4.03,64.0,446.7,4.62,1.39,3.16,2.10,1.00,0.85,0,0,0,0,1,1,0,1,1,1,0,0,0,0,0,0,1,1
121,2,55.2,157.0,58.0,23.530366,1.027,-1.3,0.9705,-0.75,0.9420,-1.15,22.0,24.0,6.36,78.7,498.0,4.62,1.07,NaN,2.10,1.13,0.83,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,1
156,1,45.0,174.0,77.0,25.432686,1.124,-0.8,0.8045,-2.00,0.7980,-2.25,18.0,9.0,28.20,NaN,645.5,6.09,0.63,0.67,2.11,2.54,0.86,0,0,0,0,1,0,0,1,1,1,0,0,0,1,1,0,1,1
161,1,40.0,169.0,75.0,26.259585,1.116,-0.9,0.9015,-1.30,0.9710,-0.90,43.0,23.0,8.66,90.0,516.8,4.35,NaN,NaN,2.20,0.94,0.86,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,0,1,1
166,1,55.0,170.0,63.0,21.799308,1.083,-1.1,0.9765,-0.70,1.0555,-0.30,21.0,15.0,5.00,100.8,445.1,NaN,0.72,2.69,2.55,1.45,0.84,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,1,1
204,1,65.9,156.0,60.0,24.654832,0.795,-3.5,0.8670,-0.95,0.9120,-0.70,28.0,19.0,5.66,76.5,523.7,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,1,0,1,0,1,1,0,0,0,1,0,0,0,0
207,1,83.0,170.0,62.0,21.453287,1.143,-0.6,0.7425,-2.00,0.7980,-1.65,10.0,17.0,7.71,70.1,367.7,5.24,1.14,1.96,2.19,NaN,0.87,0,0,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0
229,1,42.0,165.0,72.0,26.446281,1.143,-0.6,0.8835,-0.80,1.0835,0.70,12.0,13.0,4.98,97.4,368.7,4.71,1.13,3.69,2.20,NaN,0.87,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0
251,2,NaN,NaN,NaN,NaN,1.194,0.1,1.0060,-0.45,1.2045,0.85,16.0,19.0,6.57,68.7,631.3,4.77,1.14,2.72,2.16,0.90,0.91,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
259,1,52.0,168.0,69.0,24.447279,1.123,-0.8,1.0700,0.00,1.1030,0.10,56.0,17.0,5.24,79.5,352.0,5.85,NaN,NaN,2.17,1.36,0.86,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0
260,1,NaN,NaN,NaN,NaN,1.187,-0.3,1.0000,-0.55,1.0070,-0.65,37.0,24.0,4.99,72.6,443.1,4.28,0.95,3.57,2.36,1.04,0.89,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0
306,1,85.0,169.0,62.0,21.707923,1.520,2.5,0.6905,-2.45,0.6510,-2.90,39.0,27.0,4.98,48.4,254.7,6.43,NaN,NaN,2.27,1.23,1.03,1,1,0,0,1,0,0,0,0,1,0,1,1,1,0,0,0,0
336,2,NaN,NaN,NaN,NaN,1.133,-0.4,0.7220,-2.65,0.7810,-2.40,25.0,25.0,5.86,76.5,463.7,4.60,1.51,2.39,2.35,1.23,0.88,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,1
364,2,63.2,166.0,53.0,19.233561,0.838,-2.8,1.0395,-0.20,1.1585,0.50,21.0,16.0,12.05,198.3,311.9,NaN,0.80,1.51,2.14,1.25,0.70,0,0,0,0,1,1,1,0,0,1,0,0,1,1,1,0,0,0
374,2,66.1,162.0,71.0,27.053803,0.929,-2.1,0.6390,-2.80,0.7020,-2.45,17.0,23.0,9.92,74.3,232.6,NaN,1.74,1.55,2.17,0.88,0.79,0,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0,0,0
383,2,NaN,NaN,NaN,NaN,1.003,-1.5,0.7075,-2.30,0.8255,-1.45,37.0,23.0,3.83,57.7,394.2,4.95,1.08,2.49,2.17,1.14,0.82,0,0,0,0,1,0,1,1,0,1,0,0,1,0,0,0,0,0
387,2,45.0,164.0,60.0,22.308150,1.469,2.4,0.7475,-1.95,0.9210,-0.65,27.0,30.0,3.46,54.1,284.2,NaN,1.53,4.03,2.51,1.39,1.02,0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,0,0,0
394,2,82.0,158.0,55.0,22.031726,0.763,-3.5,0.7385,-2.55,0.9290,-1.20,20.0,24.0,4.64,56.8,141.2,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,0,0,0
408,2,76.2,152.0,70.0,30.297784,0.866,-2.6,0.7375,-2.05,0.7700,-1.90,37.0,20.0,7.70,117.2,243.7,NaN,0.69,1.46,2.50,1.33,0.73,0,0,0,0,1,0,1,1,0,1,0,0,1,0,0,0,0,0
414,2,52.0,161.0,60.0,23.147255,1.239,0.5,0.7610,-1.80,0.8100,-1.55,10.0,19.0,NaN,52.5,298.8,5.99,1.45,3.73,2.13,0.94,0.93,1,1,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0
426,2,64.0,148.0,61.0,27.848795,1.006,-1.5,0.5050,-3.95,0.5230,-3.95,21.0,16.0,12.05,198.3,311.9,NaN,0.80,1.51,2.21,1.17,0.82,0,0,0,0,1,1,1,0,0,1,0,0,1,0,0,0,0,0
432,2,NaN,NaN,NaN,NaN,0.903,-2.3,0.7025,-2.30,0.7425,-2.15,10.0,20.0,4.37,53.2,281.0,4.22,1.24,2.90,2.17,1.11,0.77,1,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0
444,2,NaN,NaN,NaN,NaN,1.111,-0.6,0.7390,-2.00,0.7745,-1.90,16.0,23.0,4.92,74.3,338.0,4.25,1.83,2.42,2.31,1.27,0.87,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0
449,1,64.0,178.0,80.0,25.249337,1.456,2.0,0.6695,0.30,0.7370,-2.70,28.0,31.0,7.34,78.5,369.5,NaN,0.83,3.81,2.18,1.17,1.00,1,1,0,0,1,1,0,0,0,1,0,0,1,0,0,1,1,1
456,1,54.0,173.0,80.0,26.729927,1.344,1.1,0.7005,-2.85,0.7850,-2.35,17.0,20.0,4.75,74.4,265.2,5.20,1.36,2.39,2.06,NaN,0.95,1,1,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,1
504,1,NaN,NaN,NaN,NaN,1.226,0.0,0.8160,-1.95,0.9430,-1.15,36.0,31.0,5.08,73.1,408.8,5.23,0.93,3.48,2.34,0.87,0.91,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0
519,1,47.0,171.0,68.0,23.255019,1.082,-1.2,0.7905,-1.60,0.8635,-1.15,23.0,18.0,7.67,76.6,293.3,3.86,NaN,NaN,2.34,1.15,0.84,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0,0
598,1,NaN,NaN,NaN,NaN,1.178,-0.4,0.6645,-2.65,0.8010,-1.65,16.0,21.0,5.16,91.4,389.2,4.87,1.50,3.84,2.38,0.94,0.89,0,1,0,0,0,1,0,1,0,1,0,0,1,0,0,0,0,0
611,1,NaN,NaN,NaN,NaN,1.652,3.6,0.7370,-2.00,0.7840,-1.80,18.0,22.0,5.90,58.0,215.0,4.87,1.38,1.83,2.14,2.14,1.10,0,1,1,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0
626,1,NaN,NaN,NaN,NaN,1.516,2.5,0.8545,-1.05,0.8445,-1.30,24.0,18.0,5.92,59.2,316.8,4.71,0.84,1.99,2.32,1.13,1.03,1,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,0,0
636,1,92.0,175.0,71.0,23.183673,1.280,0.5,0.6110,-3.05,0.6230,-3.10,16.0,19.0,5.70,63.3,230.8,5.62,1.51,NaN,2.41,1.12,0.93,1,1,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0
645,1,NaN,NaN,NaN,NaN,1.413,1.6,0.6815,-3.00,0.7445,-2.65,30.0,36.0,3.85,90.1,285.5,4.42,1.43,2.67,2.13,1.00,0.99,0,1,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0
654,1,49.7,174.0,79.0,26.093275,1.375,1.3,0.7595,-2.40,0.8725,-1.65,58.0,36.0,4.76,88.6,283.6,4.67,1.15,NaN,2.10,0.92,0.97,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0
663,1,70.0,173.0,66.0,22.052190,0.903,-2.6,0.7135,-2.25,0.7855,-1.80,28.0,26.0,4.76,52.9,254.6,NaN,NaN,NaN,2.21,1.40,0.74,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0
681,2,60.8,162.0,66.0,25.148605,0.858,-2.7,0.7495,-1.90,0.8270,-1.45,28.0,31.0,6.44,63.2,238.8,NaN,NaN,NaN,2.31,1.69,0.72,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
716,1,50.2,170.0,73.0,25.259516,0.993,-1.9,0.6835,-3.00,0.8375,-1.95,26.0,16.0,6.76,79.8,350.4,NaN,0.85,3.50,2.30,1.20,0.80,0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,1,0
784,2,NaN,NaN,NaN,NaN,1.235,0.5,0.8690,-1.55,0.9065,-1.40,15.0,21.0,4.82,88.2,349.7,5.66,1.15,2.69,2.32,0.87,0.93,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0
846,2,NaN,NaN,NaN,NaN,1.219,0.3,0.8675,-1.55,1.0320,-0.45,21.0,25.0,8.83,89.3,385.4,5.53,1.01,3.48,2.14,0.94,0.92,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0
906,2,NaN,NaN,NaN,NaN,0.963,-1.8,1.0665,-0.05,1.0705,-0.15,70.0,49.0,4.52,73.8,278.7,8.13,0.85,2.59,2.24,0.80,0.81,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0
965,2,NaN,NaN,NaN,NaN,0.890,-2.4,1.0210,0.35,0.9800,-0.20,29.0,28.0,4.03,57.2,272.7,4.22,1.47,2.90,2.04,0.98,0.76,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
990,1,NaN,NaN,NaN,NaN,1.014,-1.7,0.9280,-1.10,1.0030,-0.65,14.0,15.0,7.38,103.9,325.7,10.59,1.73,5.49,2.30,1.06,0.81,0,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,1,1
1037,1,68.0,167.0,86.0,30.836531,0.969,-2.1,0.9815,-0.70,1.0930,0.05,39.0,28.0,6.54,72.1,401.0,4.93,NaN,2.93,2.18,1.10,0.79,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,1
1044,1,NaN,171.0,58.0,19.835163,1.137,-0.7,1.0040,-0.50,1.0990,0.05,14.0,17.0,3.26,62.6,309.1,5.41,1.02,3.30,1.90,1.08,0.87,0,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,1
1057,1,51.1,150.0,48.0,21.333333,0.970,-2.1,0.8965,-1.35,0.9295,-1.25,29.0,22.0,6.19,72.0,310.0,NaN,NaN,NaN,2.23,1.10,0.79,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
1067,1,53.0,187.0,91.0,26.023049,1.372,1.3,0.7595,-2.40,0.8425,-1.90,27.0,23.0,4.62,NaN,328.8,6.12,1.10,3.66,2.31,0.74,0.97,0,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,1,0
1076,1,50.0,178.0,70.0,22.093170,1.126,-0.8,0.9985,-0.55,1.1205,0.25,NaN,NaN,3.98,78.3,411.3,5.80,0.55,2.62,2.09,0.83,0.87,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0
1079,1,NaN,NaN,NaN,NaN,1.018,-1.7,0.8345,-1.80,0.9585,-1.00,23.0,22.0,4.81,80.7,356.6,5.40,1.00,1.15,2.19,1.10,0.81,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,1,0
1088,1,60.0,168.0,70.0,24.801587,1.189,-0.3,0.8935,-0.75,0.9285,-0.60,43.0,28.0,6.82,57.7,287.9,4.52,NaN,4.06,2.38,1.06,0.89,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0
1105,1,42.7,174.0,78.5,25.928128,0.807,-3.4,0.8580,-1.60,0.9105,-1.35,26.0,33.0,9.80,127.6,281.1,5.12,NaN,1.41,2.36,1.08,0.59,0,1,0,0,1,1,1,0,0,1,0,0,0,1,0,0,0,0
1108,1,NaN,NaN,NaN,NaN,0.996,-1.9,0.8705,-0.90,0.9425,-0.45,14.0,24.0,7.70,81.0,241.5,5.54,0.87,1.58,2.32,1.29,0.80,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0
1177,1,54.0,175.0,80.0,26.122449,1.201,-0.2,0.8280,-1.85,0.9210,-1.30,13.0,22.0,3.10,57.1,243.0,5.14,NaN,3.02,2.23,0.75,0.90,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0
1187,1,NaN,NaN,NaN,NaN,1.123,-0.8,0.9935,0.10,1.1140,0.95,25.0,22.0,4.39,56.4,318.6,NaN,0.92,2.34,2.48,1.33,0.86,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0
1227,1,65.0,161.0,41.0,15.817291,0.802,-3.5,0.9405,-0.30,1.0590,0.50,32.0,21.0,5.83,66.9,273.2,4.79,1.88,2.81,2.26,0.99,NaN,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0
1245,1,NaN,NaN,NaN,NaN,1.145,-0.6,1.0640,-0.05,1.0160,-0.55,14.0,16.0,6.30,62.1,363.3,5.17,1.02,2.41,2.33,0.79,0.88,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1284,2,NaN,NaN,NaN,NaN,1.030,-1.3,0.8195,-1.35,0.8925,-0.85,36.0,22.0,3.36,46.6,249.5,4.21,1.12,1.63,2.29,1.15,0.83,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1293,2,NaN,NaN,NaN,NaN,1.310,1.1,0.8730,-0.90,0.9115,-0.75,12.0,16.0,6.70,58.5,277.4,4.06,1.35,2.47,2.28,1.55,0.95,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1312,2,NaN,NaN,NaN,NaN,0.909,-2.3,0.7895,-1.60,0.8000,-1.70,12.0,15.0,5.10,57.7,283.1,4.76,1.53,3.31,2.27,1.17,0.77,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1326,2,NaN,NaN,NaN,NaN,0.838,-2.9,1.1895,0.90,1.2810,1.45,24.0,45.0,5.00,66.7,399.6,8.47,0.85,2.41,2.25,1.14,0.70,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1327,2,50.6,155.0,62.0,25.806452,0.991,-1.6,0.7080,-2.25,0.7085,-2.45,52.0,38.0,5.92,55.0,280.9,NaN,0.96,3.22,2.40,1.34,0.81,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1350,2,NaN,NaN,NaN,NaN,0.978,-1.7,0.8960,-0.70,0.8955,-0.85,9.0,17.0,4.10,69.0,219.1,4.56,1.37,1.89,2.34,1.02,0.81,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1370,1,NaN,NaN,NaN,NaN,1.509,2.4,1.1100,0.35,1.0970,0.05,17.0,16.0,6.75,80.1,342.6,4.96,1.49,3.29,2.25,0.92,1.03,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,1
1378,1,64.0,175.0,90.0,29.387755,1.523,2.5,1.0885,0.15,1.0460,-0.30,36.0,25.0,6.21,111.9,419.0,5.18,NaN,NaN,2.19,1.56,1.03,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
1379,1,NaN,NaN,NaN,NaN,1.207,-0.1,0.8740,-1.50,0.9340,-1.20,21.0,20.0,6.31,78.8,424.8,4.31,1.01,1.64,2.27,1.00,0.90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
1405,1,NaN,NaN,NaN,NaN,1.071,-1.2,0.9175,-1.20,1.0550,-0.25,22.0,16.0,4.91,58.7,299.4,7.18,1.20,2.27,2.33,1.01,0.84,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1406,1,NaN,NaN,NaN,NaN,1.284,0.5,0.8080,-1.45,0.8815,-1.00,126.0,96.0,4.26,59.1,359.2,5.06,1.30,3.28,2.25,1.18,0.93,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1425,1,NaN,NaN,NaN,NaN,1.194,-0.2,0.7595,-1.85,0.8055,-1.65,19.0,26.0,4.60,59.8,328.1,4.93,1.57,2.36,2.42,1.19,0.89,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1426,1,NaN,NaN,NaN,NaN,0.894,-2.7,0.9005,-0.70,0.9105,-3.90,9.0,15.0,4.20,48.2,313.9,4.48,NaN,3.25,2.36,1.02,0.73,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1443,1,50.0,174.0,78.0,25.762981,1.156,-0.5,0.9505,0.10,0.8320,-2.00,15.0,19.0,3.45,69.9,307.4,7.50,NaN,1.81,2.09,1.02,0.88,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0
1473,1,NaN,NaN,NaN,NaN,1.157,-0.5,0.8170,-1.35,0.8650,-1.10,27.0,22.0,5.50,74.0,572.0,4.30,1.31,3.02,2.39,1.02,0.88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1501,1,57.6,176.0,75.0,24.212293,1.212,-0.1,0.7940,-1.55,0.9655,-0.25,NaN,NaN,3.03,49.5,261.0,4.89,1.34,1.93,2.30,1.09,0.90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1514,1,45.0,168.0,82.0,29.053288,0.973,-2.1,0.7855,-1.60,0.8860,-0.95,24.0,22.0,3.23,51.7,223.6,5.43,NaN,NaN,2.42,1.30,0.79,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
filtered_rows = df[
    (df['Age'].notnull()) &
    (df.isnull().any(axis=1))
]

filtered_rows

,Gender,Age,Height,Weight,BMI,L1-4,L1.4T,FN,FNT,TL,TLT,ALT,AST,BUN,CREA,URIC,FBG,HDL-C,LDL-C,Ca,P,Mg,Calsium,Calcitriol,Bisphosphonate,Calcitonin,HTN,COPD,DM,Hyperlipidaemia,Hyperuricemia,AS,VT,VD,OP,CAD,CKD,Fracture,Smoking,Drinking
43,1,74.7,177.0,78.0,24.897060,1.431,1.8,0.8410,-1.80,0.9355,-1.20,74.0,29.0,4.30,NaN,551.0,NaN,1.03,4.53,2.31,1.25,0.99,0,0,0,0,1,0,1,1,1,1,0,0,1,0,0,0,0,1
121,2,55.2,157.0,58.0,23.530366,1.027,-1.3,0.9705,-0.75,0.9420,-1.15,22.0,24.0,6.36,78.7,498.0,4.62,1.07,NaN,2.10,1.13,0.83,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,1
156,1,45.0,174.0,77.0,25.432686,1.124,-0.8,0.8045,-2.00,0.7980,-2.25,18.0,9.0,28.20,NaN,645.5,6.09,0.63,0.67,2.11,2.54,0.86,0,0,0,0,1,0,0,1,1,1,0,0,0,1,1,0,1,1
161,1,40.0,169.0,75.0,26.259585,1.116,-0.9,0.9015,-1.30,0.9710,-0.90,43.0,23.0,8.66,90.0,516.8,4.35,NaN,NaN,2.20,0.94,0.86,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,0,1,1
166,1,55.0,170.0,63.0,21.799308,1.083,-1.1,0.9765,-0.70,1.0555,-0.30,21.0,15.0,5.00,100.8,445.1,NaN,0.72,2.69,2.55,1.45,0.84,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,1,1
204,1,65.9,156.0,60.0,24.654832,0.795,-3.5,0.8670,-0.95,0.9120,-0.70,28.0,19.0,5.66,76.5,523.7,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,1,0,1,0,1,1,0,0,0,1,0,0,0,0
207,1,83.0,170.0,62.0,21.453287,1.143,-0.6,0.7425,-2.00,0.7980,-1.65,10.0,17.0,7.71,70.1,367.7,5.24,1.14,1.96,2.19,NaN,0.87,0,0,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0
229,1,42.0,165.0,72.0,26.446281,1.143,-0.6,0.8835,-0.80,1.0835,0.70,12.0,13.0,4.98,97.4,368.7,4.71,1.13,3.69,2.20,NaN,0.87,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0
259,1,52.0,168.0,69.0,24.447279,1.123,-0.8,1.0700,0.00,1.1030,0.10,56.0,17.0,5.24,79.5,352.0,5.85,NaN,NaN,2.17,1.36,0.86,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0
306,1,85.0,169.0,62.0,21.707923,1.520,2.5,0.6905,-2.45,0.6510,-2.90,39.0,27.0,4.98,48.4,254.7,6.43,NaN,NaN,2.27,1.23,1.03,1,1,0,0,1,0,0,0,0,1,0,1,1,1,0,0,0,0
364,2,63.2,166.0,53.0,19.233561,0.838,-2.8,1.0395,-0.20,1.1585,0.50,21.0,16.0,12.05,198.3,311.9,NaN,0.80,1.51,2.14,1.25,0.70,0,0,0,0,1,1,1,0,0,1,0,0,1,1,1,0,0,0
374,2,66.1,162.0,71.0,27.053803,0.929,-2.1,0.6390,-2.80,0.7020,-2.45,17.0,23.0,9.92,74.3,232.6,NaN,1.74,1.55,2.17,0.88,0.79,0,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0,0,0
387,2,45.0,164.0,60.0,22.308150,1.469,2.4,0.7475,-1.95,0.9210,-0.65,27.0,30.0,3.46,54.1,284.2,NaN,1.53,4.03,2.51,1.39,1.02,0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,0,0,0
394,2,82.0,158.0,55.0,22.031726,0.763,-3.5,0.7385,-2.55,0.9290,-1.20,20.0,24.0,4.64,56.8,141.2,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,0,0,0
408,2,76.2,152.0,70.0,30.297784,0.866,-2.6,0.7375,-2.05,0.7700,-1.90,37.0,20.0,7.70,117.2,243.7,NaN,0.69,1.46,2.50,1.33,0.73,0,0,0,0,1,0,1,1,0,1,0,0,1,0,0,0,0,0
414,2,52.0,161.0,60.0,23.147255,1.239,0.5,0.7610,-1.80,0.8100,-1.55,10.0,19.0,NaN,52.5,298.8,5.99,1.45,3.73,2.13,0.94,0.93,1,1,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0
426,2,64.0,148.0,61.0,27.848795,1.006,-1.5,0.5050,-3.95,0.5230,-3.95,21.0,16.0,12.05,198.3,311.9,NaN,0.80,1.51,2.21,1.17,0.82,0,0,0,0,1,1,1,0,0,1,0,0,1,0,0,0,0,0
449,1,64.0,178.0,80.0,25.249337,1.456,2.0,0.6695,0.30,0.7370,-2.70,28.0,31.0,7.34,78.5,369.5,NaN,0.83,3.81,2.18,1.17,1.00,1,1,0,0,1,1,0,0,0,1,0,0,1,0,0,1,1,1
456,1,54.0,173.0,80.0,26.729927,1.344,1.1,0.7005,-2.85,0.7850,-2.35,17.0,20.0,4.75,74.4,265.2,5.20,1.36,2.39,2.06,NaN,0.95,1,1,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,1
519,1,47.0,171.0,68.0,23.255019,1.082,-1.2,0.7905,-1.60,0.8635,-1.15,23.0,18.0,7.67,76.6,293.3,3.86,NaN,NaN,2.34,1.15,0.84,1,0,0,0,1,0,1,0,0,1,0,0,1,0,0,1,0,0
636,1,92.0,175.0,71.0,23.183673,1.280,0.5,0.6110,-3.05,0.6230,-3.10,16.0,19.0,5.70,63.3,230.8,5.62,1.51,NaN,2.41,1.12,0.93,1,1,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0
654,1,49.7,174.0,79.0,26.093275,1.375,1.3,0.7595,-2.40,0.8725,-1.65,58.0,36.0,4.76,88.6,283.6,4.67,1.15,NaN,2.10,0.92,0.97,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0
663,1,70.0,173.0,66.0,22.052190,0.903,-2.6,0.7135,-2.25,0.7855,-1.80,28.0,26.0,4.76,52.9,254.6,NaN,NaN,NaN,2.21,1.40,0.74,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0
681,2,60.8,162.0,66.0,25.148605,0.858,-2.7,0.7495,-1.90,0.8270,-1.45,28.0,31.0,6.44,63.2,238.8,NaN,NaN,NaN,2.31,1.69,0.72,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
716,1,50.2,170.0,73.0,25.259516,0.993,-1.9,0.6835,-3.00,0.8375,-1.95,26.0,16.0,6.76,79.8,350.4,NaN,0.85,3.50,2.30,1.20,0.80,0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,1,0
1037,1,68.0,167.0,86.0,30.836531,0.969,-2.1,0.9815,-0.70,1.0930,0.05,39.0,28.0,6.54,72.1,401.0,4.93,NaN,2.93,2.18,1.10,0.79,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,1
1057,1,51.1,150.0,48.0,21.333333,0.970,-2.1,0.8965,-1.35,0.9295,-1.25,29.0,22.0,6.19,72.0,310.0,NaN,NaN,NaN,2.23,1.10,0.79,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
1067,1,53.0,187.0,91.0,26.023049,1.372,1.3,0.7595,-2.40,0.8425,-1.90,27.0,23.0,4.62,NaN,328.8,6.12,1.10,3.66,2.31,0.74,0.97,0,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,1,0
1076,1,50.0,178.0,70.0,22.093170,1.126,-0.8,0.9985,-0.55,1.1205,0.25,NaN,NaN,3.98,78.3,411.3,5.80,0.55,2.62,2.09,0.83,0.87,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0
1088,1,60.0,168.0,70.0,24.801587,1.189,-0.3,0.8935,-0.75,0.9285,-0.60,43.0,28.0,6.82,57.7,287.9,4.52,NaN,4.06,2.38,1.06,0.89,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0
1105,1,42.7,174.0,78.5,25.928128,0.807,-3.4,0.8580,-1.60,0.9105,-1.35,26.0,33.0,9.80,127.6,281.1,5.12,NaN,1.41,2.36,1.08,0.59,0,1,0,0,1,1,1,0,0,1,0,0,0,1,0,0,0,0
1177,1,54.0,175.0,80.0,26.122449,1.201,-0.2,0.8280,-1.85,0.9210,-1.30,13.0,22.0,3.10,57.1,243.0,5.14,NaN,3.02,2.23,0.75,0.90,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0
1227,1,65.0,161.0,41.0,15.817291,0.802,-3.5,0.9405,-0.30,1.0590,0.50,32.0,21.0,5.83,66.9,273.2,4.79,1.88,2.81,2.26,0.99,NaN,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0
1327,2,50.6,155.0,62.0,25.806452,0.991,-1.6,0.7080,-2.25,0.7085,-2.45,52.0,38.0,5.92,55.0,280.9,NaN,0.96,3.22,2.40,1.34,0.81,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1378,1,64.0,175.0,90.0,29.387755,1.523,2.5,1.0885,0.15,1.0460,-0.30,36.0,25.0,6.21,111.9,419.0,5.18,NaN,NaN,2.19,1.56,1.03,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
1443,1,50.0,174.0,78.0,25.762981,1.156,-0.5,0.9505,0.10,0.8320,-2.00,15.0,19.0,3.45,69.9,307.4,7.50,NaN,1.81,2.09,1.02,0.88,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0
1501,1,57.6,176.0,75.0,24.212293,1.212,-0.1,0.7940,-1.55,0.9655,-0.25,NaN,NaN,3.03,49.5,261.0,4.89,1.34,1.93,2.30,1.09,0.90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1514,1,45.0,168.0,82.0,29.053288,0.973,-2.1,0.7855,-1.60,0.8860,-0.95,24.0,22.0,3.23,51.7,223.6,5.43,NaN,NaN,2.42,1.30,0.79,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
filtered_rows.shape

(38, 40)

In [ ]:
filtered_rows.isnull().sum()

Gender              0
Age                 0
Height              0
Weight              0
BMI                 0
L1-4                0
L1.4T               0
FN                  0
FNT                 0
TL                  0
TLT                 0
ALT                 2
AST                 2
BUN                 1
CREA                3
URIC                0
FBG                15
HDL-C              16
LDL-C              14
Ca                  2
P                   5
Mg                  3
Calsium             0
Calcitriol          0
Bisphosphonate      0
Calcitonin          0
HTN                 0
COPD                0
DM                  0
Hyperlipidaemia     0
Hyperuricemia       0
AS                  0
VT                  0
VD                  0
OP                  0
CAD                 0
CKD                 0
Fracture            0
Smoking             0
Drinking            0
dtype: int64

In [ ]:
df['Fracture'].value_counts()

Fracture
0    1506
1      31
Name: count, dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.shape

(1463, 40)

In [ ]:
df.to_csv("../data/processed/cleaned_UA.csv", index=False)

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [29]:
# Create recommended features dataset from cleaned_UA.csv
import pandas as pd

in_path = "../data/processed/cleaned_UA.csv"
out_path = "../data/processed/reccomended_features_dataset.csv"

# Select the desired columns — note 'Smoking' and 'Drinking' are separate, and target is 'Fracture'
selected = [
    "Gender",
    "Age",
    "Height",
    "Weight",
    "BMI",
    "Smoking",
    "Drinking",
    "Fracture",
]

# Load cleaned data
df_clean = pd.read_csv(in_path)

# Check for missing columns and report
missing = [c for c in selected if c not in df_clean.columns]
if missing:
    print(f"Warning: the following requested columns are missing in {in_path}: {missing}")

rec_df = df_clean[[c for c in selected if c in df_clean.columns]].copy()

# Save recommended dataset
rec_df.to_csv(out_path, index=False)
print(f"Saved {rec_df.shape[0]} rows x {rec_df.shape[1]} cols to {out_path}")

# Display a quick preview
rec_df.head()

Saved 1463 rows x 8 cols to ../data/processed/reccomended_features_dataset.csv

   Gender   Age  Height  Weight        BMI  Smoking  Drinking  Fracture
0       2  61.9   164.0    47.0  17.474717        1         0         0
1       2  55.0   162.0    54.0  20.576132        0         0         0
2       2  44.0   160.0    54.0  21.093750        0         0         0
3       1  64.7   158.0    59.0  23.634033        1         1         0
4       1  88.5   167.0    60.0  21.513859        1         0         0

In [31]:
# Inspect `cleaned_UA.csv` columns to locate target and smoking/drinking columns
import pandas as pd

_check_path = "../data/processed/cleaned_UA.csv"
_clean = pd.read_csv(_check_path)
print("cleaned_UA.csv shape:", _clean.shape)
print("columns:", _clean.columns.tolist())
_clean.head(3)

cleaned_UA.csv shape: (1463, 40)
columns: ['Gender', 'Age', 'Height', 'Weight', 'BMI', 'L1-4', 'L1.4T', 'FN', 'FNT', 'TL', 'TLT', 'ALT', 'AST', 'BUN', 'CREA', 'URIC', 'FBG', 'HDL-C', 'LDL-C', 'Ca', 'P', 'Mg', 'Calsium', 'Calcitriol', 'Bisphosphonate', 'Calcitonin', 'HTN', 'COPD', 'DM', 'Hyperlipidaemia', 'Hyperuricemia', 'AS', 'VT', 'VD', 'OP', 'CAD', 'CKD', 'Fracture', 'Smoking', 'Drinking']

,Gender,Age,Height,Weight,BMI,L1-4,L1.4T,FN,FNT,TL,TLT,ALT,AST,BUN,CREA,URIC,FBG,HDL-C,LDL-C,Ca,P,Mg,Calsium,Calcitriol,Bisphosphonate,Calcitonin,HTN,COPD,DM,Hyperlipidaemia,Hyperuricemia,AS,VT,VD,OP,CAD,CKD,Fracture,Smoking,Drinking
0,2,61.9,164.0,47.0,17.474717,0.894,-2.4,0.6895,-2.95,0.7130,-2.90,17.0,21.0,8.10,84.8,265.4,4.55,1.16,2.06,2.15,1.04,0.76,1,1,0,0,1,1,0,0,1,1,0,1,1,1,0,0,1,0
1,2,55.0,162.0,54.0,20.576132,1.333,1.3,0.9130,-1.30,1.0675,-0.15,34.0,25.0,7.64,85.0,466.0,3.89,1.22,2.35,2.15,1.11,0.96,1,0,0,0,1,0,1,0,1,1,0,1,1,0,1,0,0,0
2,2,44.0,160.0,54.0,21.093750,1.157,-0.2,0.5190,-3.85,0.5770,-3.55,11.0,21.0,5.14,76.2,479.1,4.66,1.54,1.65,2.18,1.10,0.89,1,1,0,1,1,1,1,0,1,1,0,1,1,1,0,0,0,0

In [30]:
# Split `reccomended_features_dataset.csv` into 90/10 train/test and save (robust target detection)
import pandas as pd

# Ensure scikit-learn is available in the notebook kernel; install if missing
try:
    from sklearn.model_selection import train_test_split
except ModuleNotFoundError:
    import sys, subprocess
    print("scikit-learn not found in kernel; installing into kernel environment...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "scikit-learn"]) 
    from sklearn.model_selection import train_test_split

in_path = "../data/processed/reccomended_features_dataset.csv"
train_path = "../data/processed/train_reccomended_features.csv"
test_path = "../data/processed/test_reccomended_features.csv"

# Load the recommended dataset
df_rec = pd.read_csv(in_path)
print("Loaded rec dataset:", df_rec.shape)
print("Columns:", list(df_rec.columns))

# Robust target finder: match column names containing 'fracture' (ignore case/spaces/underscores)
def find_target(cols, name="fracture"):
    name_clean = name.lower().replace(" ", "").replace("_", "")
    for c in cols:
        c_clean = c.lower().replace(" ", "").replace("_", "")
        if name_clean in c_clean:
            return c
    return None

target_col = find_target(df_rec.columns, "fracture")
if target_col is None:
    raise ValueError(f"Target column containing 'fracture' not found. Available columns: {list(df_rec.columns)}")

print(f"Using target column: {target_col}")

# Drop rows with missing target
missing_target = df_rec[target_col].isnull().sum()
if missing_target:
    print(f"Dropping {missing_target} rows with missing target '{target_col}'")
    df_rec = df_rec[df_rec[target_col].notnull()].copy()

X = df_rec.drop(columns=[target_col])
y = df_rec[target_col]

# Determine stratify param only when there are >=2 classes
stratify_param = y if y.nunique() > 1 else None

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.1, stratify=stratify_param, random_state=42
)

train_df = pd.concat([X_train, y_train], axis=1)
test_df = pd.concat([X_test, y_test], axis=1)

train_df.to_csv(train_path, index=False)
test_df.to_csv(test_path, index=False)

print(f"Saved train: {train_df.shape} -> {train_path}")
print(f"Saved test:  {test_df.shape} -> {test_path}")

train_df.head()

Loaded rec dataset: (1463, 8)
Columns: ['Gender', 'Age', 'Height', 'Weight', 'BMI', 'Smoking', 'Drinking', 'Fracture']
Using target column: Fracture
Saved train: (1316, 8) -> ../data/processed/train_reccomended_features.csv
Saved test:  (147, 8) -> ../data/processed/test_reccomended_features.csv

      Gender   Age  Height  Weight        BMI  Smoking  Drinking  Fracture
436        1  81.8   168.0    78.0  27.636054        1         1         0
546        1  73.0   178.0    74.0  23.355637        0         0         0
1415       1  47.0   176.0    82.0  26.472107        0         0         0
1260       2  32.8   167.0    61.0  21.872423        0         0         0
179        1  42.4   171.0    70.0  23.938990        0         1         0

In [2]:
# EDA plots for the recommended features dataset
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

train_path = "../data/processed/train_reccomended_features.csv"
plots_dir = "../outputs/plots"
os.makedirs(plots_dir, exist_ok=True)

# Load training data only for EDA to avoid test leakage
eda_df = pd.read_csv(train_path)

# Ensure the expected columns exist
expected_cols = ["Gender", "Age", "Height", "Weight", "BMI", "Smoking", "Drinking", "Fracture"]
missing_cols = [col for col in expected_cols if col not in eda_df.columns]
if missing_cols:
    raise ValueError(f"Missing columns in {train_path}: {missing_cols}")

# Force numeric values for plotting
for col in ["Age", "Height", "Weight", "BMI", "Smoking", "Drinking", "Fracture"]:
    eda_df[col] = pd.to_numeric(eda_df[col], errors="coerce")

sns.set_theme(style="whitegrid", context="talk")

saved_plots = []

def save_current_figure(filename):
    full_path = os.path.join(plots_dir, filename)
    plt.savefig(full_path, dpi=200, bbox_inches="tight")
    saved_plots.append(full_path)
    plt.close()

# 1) Target class balance
fig, ax = plt.subplots(figsize=(7, 5))
fracture_order = sorted(eda_df["Fracture"].dropna().unique().tolist())
sns.countplot(data=eda_df, x="Fracture", order=fracture_order, color="#4c72b0", ax=ax)
ax.set_title("Fracture Class Balance")
ax.set_xlabel("Fracture")
ax.set_ylabel("Count")
for container in ax.containers:
    ax.bar_label(container)
save_current_figure("01_fracture_class_balance.png")

# 2) Age distribution
fig, ax = plt.subplots(figsize=(8, 5))
sns.histplot(eda_df["Age"].dropna(), bins=30, kde=True, color="#2a9d8f", ax=ax)
ax.set_title("Age Distribution")
ax.set_xlabel("Age")
ax.set_ylabel("Count")
save_current_figure("02_age_distribution.png")

# 3) BMI distribution
fig, ax = plt.subplots(figsize=(8, 5))
sns.histplot(eda_df["BMI"].dropna(), bins=30, kde=True, color="#e76f51", ax=ax)
ax.set_title("BMI Distribution")
ax.set_xlabel("BMI")
ax.set_ylabel("Count")
save_current_figure("03_bmi_distribution.png")

# 4) Height distribution
fig, ax = plt.subplots(figsize=(8, 5))
sns.histplot(eda_df["Height"].dropna(), bins=30, kde=True, color="#457b9d", ax=ax)
ax.set_title("Height Distribution")
ax.set_xlabel("Height")
ax.set_ylabel("Count")
save_current_figure("04_height_distribution.png")

# 5) Weight distribution
fig, ax = plt.subplots(figsize=(8, 5))
sns.histplot(eda_df["Weight"].dropna(), bins=30, kde=True, color="#8d99ae", ax=ax)
ax.set_title("Weight Distribution")
ax.set_xlabel("Weight")
ax.set_ylabel("Count")
save_current_figure("05_weight_distribution.png")

# 6) Correlation heatmap
fig, ax = plt.subplots(figsize=(10, 8))
correlation_cols = ["Age", "Height", "Weight", "BMI", "Smoking", "Drinking", "Fracture"]
corr = eda_df[correlation_cols].corr()
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", center=0, square=True, linewidths=0.5, ax=ax)
ax.set_title("Correlation Heatmap")
save_current_figure("06_correlation_heatmap.png")

# 7) Fracture vs Smoking/Drinking grouped bar chart
fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)
feature_hues = [("Smoking", "Fracture vs Smoking"), ("Drinking", "Fracture vs Drinking")]
for axis, (hue_col, title) in zip(axes, feature_hues):
    hue_order = sorted(eda_df[hue_col].dropna().unique().tolist())
    sns.countplot(
        data=eda_df,
        x="Fracture",
        hue=hue_col,
        order=fracture_order,
        hue_order=hue_order,
        palette="Set2",
        ax=axis,
    )
    axis.set_title(title)
    axis.set_xlabel("Fracture")
    axis.set_ylabel("Count")
    axis.legend(title=hue_col, loc="upper right")
fig.suptitle("Fracture vs Smoking/Drinking Grouped Bar Charts", y=1.02)
fig.tight_layout()
plt.savefig(os.path.join(plots_dir, "07_fracture_vs_smoking_drinking_grouped_bars.png"), dpi=200, bbox_inches="tight")
saved_plots.append(os.path.join(plots_dir, "07_fracture_vs_smoking_drinking_grouped_bars.png"))
plt.close(fig)

print("Saved plots:")
for plot_path in saved_plots:
    print(plot_path)

Saved plots:
../outputs/plots\01_fracture_class_balance.png
../outputs/plots\02_age_distribution.png
../outputs/plots\03_bmi_distribution.png
../outputs/plots\04_height_distribution.png
../outputs/plots\05_weight_distribution.png
../outputs/plots\06_correlation_heatmap.png
../outputs/plots\07_fracture_vs_smoking_drinking_grouped_bars.png